service: cat

provider:
  name: aws
  runtime: python3.8

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.lambda_handler
    events:
      - http:
          path: hello
          method: get

